kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-block-csi-controller
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.2.1
        - name: csi-attacher
          image:  k8s.gcr.io/sig-storage/csi-attacher:v3.5.0
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.6.0
        - name: iks-vpc-block-driver
          imagePullPolicy: Always
          image: k8s.gcr.io/cloud-provider-ibm/ibm-vpc-block-csi-driver:v0.0.0
        - name: csi-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.5.0
        - name: csi-snapshotter
          image: k8s.gcr.io/sig-storage/csi-snapshotter:v6.0.1
