apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10 # Update vpc data volume size which should match as per pv's size
  storageClassName: ""
